backend:
  name: git-gateway
  branch: master

# media_folder: static/img
# public_folder: /img

media_folder: src/pages/case-study/img
public_folder: case-study/img

collections:
  - name: "case-study"
    label: "Case Studies"
    folder: "src/pages/case-study"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-study"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tile Size", name: "tilesize", widget: "select", options: ["col-12", "col-11", "col-10", "col-9", "col-8", "col-7", "col-6", "col-5", "col-4", "col-3", "col-2", "col-1"]}
      - {label: "Push Right", name: "pushright", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image 1", name: "image1", widget: image}
      - {label: "Image 2", name: "image2", widget: image, required: false}
      - {label: "Image 3", name: "image3", widget: image, required: false}
      - {label: "Image 4", name: "image4", widget: image, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Manifesto, name: manifesto, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
