backend:
  name: git-gateway
  branch: master

# media_folder: static/img
# public_folder: /img

media_folder: static/img
public_folder: /img

collections:
  - name: "case-study"
    label: "Case Studies"
    folder: "src/pages/case-study"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-study"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tile Size", name: "tilesize", widget: "select", options: ["col-12", "col-11", "col-10", "col-9", "col-8", "col-7", "col-6", "col-5", "col-4", "col-3", "col-2", "col-1"]}
      - {label: "Push Right", name: "pushright", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: Main, name: main, widget: object, fields: [{label: Row1, name: row1, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image},{label: Image3, name: image3, widget:image}],label: Row2, name: row2, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row3, name: row3, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row4, name: row4, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row5, name: row5, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row6, name: row6, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row7, name: row7, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row8, name: row8, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row9, name: row9, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row10, name: row10, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row11, name: row11, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image}, {label: Image3, name: image3, widget: image}],label: Row12, name: row12, widget: object, fields: [{label: Row Layout, name: rowLayout, widget: string},{label: Image1, name: image1, widget: image},{label: Image2, name: image2, widget: image},{label: Image3, name: image3, widget: image}]}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Manifesto, name: manifesto, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
